# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Ov < Formula
  desc "Feature rich terminal pager"
  homepage "https://github.com/noborus/ov"
  version "0.13.0"

  on_macos do
    if Hardware::CPU.arm?
      url "https://github.com/noborus/ov/releases/download/v0.13.0/ov_0.13.0_darwin_arm64.zip"
      sha256 "0cac1c9761f851f7b8dff8960d1434c55a5769228f2170a382696d2bf8cc9773"

      def install
        bin.install "ov"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/noborus/ov/releases/download/v0.13.0/ov_0.13.0_darwin_amd64.zip"
      sha256 "9253eb8b2e717e8e5a8a84f69dadda5d8ba01a7fbd44d909e71f40c4bc9749dd"

      def install
        bin.install "ov"
      end
    end
  end

  on_linux do
    if Hardware::CPU.arm? && !Hardware::CPU.is_64_bit?
      url "https://github.com/noborus/ov/releases/download/v0.13.0/ov_0.13.0_linux_arm.zip"
      sha256 "0af511f07f800d2684a5c0cc35148c672f2e12a943972a16dd888af4fd8d01f9"

      def install
        bin.install "ov"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/noborus/ov/releases/download/v0.13.0/ov_0.13.0_linux_amd64.zip"
      sha256 "deea887d6eadf4b612869568b30cfe6f35c2e738970f57a233716868bcf0b707"

      def install
        bin.install "ov"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/noborus/ov/releases/download/v0.13.0/ov_0.13.0_linux_arm64.zip"
      sha256 "452a8921376822a07c154edfbf886d611c9ce1c4db2c701a03f66c981b8280d5"

      def install
        bin.install "ov"
      end
    end
  end

  test do
    system "#{bin}/ov --version"
  end
end
